### ISSUE TITLE
High CPU Usage + FanControl Interruptions

### ISSUE THREAD

**Issue by onestix** [brokenmass/AIOLCDUnchained#5]
@brokenmass before I start, I wanted to thank you for this cool project. I have just bumped across this, while being a long time user of your FanControl plugin. This project is a savior because I can now elegantly use my AIO display in conjunction with FanControl.

Now to my issue- I was wondering if anyone else is experiencing high CPU usage when running this bridge?  I am observing a constant 3-5% CPU usage when setting a "static" background (Solid Color) for my AIO via SignalRGB, which I find quite high. To give some context, I am running on a 13700k with Windows 11, Z53, FanControl (including the [Fancontrol.NzxtKraken plugin](https://github.com/brokenmass/Fancontrol.NzxtKraken)). Could this perhaps be related to the fact that I have the bridge running concurrently with the FanControl plugin? I do notice in FanControl that the Fan and Pump are being interrupted by the bridge every 2-3 seconds, with an exclamation mark showing up next to the fan+pump:

![image](https://github.com/brokenmass/AIOLCDUnchained/assets/84330001/9bde1b0a-9c00-4986-a39e-3e04c1fd8dca)

I assume this is happening because the Kraken only allows one program to access it at a time? Also, I had to change the Liquid Temperature readings from the Fancontrol.NzxtKraken plugin to the available LibreHardware values, because the Fancontrol.NzxtKraken readings were jumping to 0 every 2-3 secs, making the AIO pump and fan constantly restart themselves. I really wonder if the setup I have in place is the correct way of using both applications (FanControl plugin + SignalRGB bridge)?

Thanks again and I´d appreciate hearing some tips here.

**Comment by brokenmass** [comment]
@onestix your proposal to introduce a fps limit configuration in signalrgb was amazing and I've implemented it ! https://github.com/brokenmass/AIOLCDUnchained/releases/tag/v1.2.0
